### ISSUE TITLE
It would be great if a sample nginx conf file was made available for autodiscover

### ISSUE THREAD

**Issue by ianb445** [Monogramm/autodiscover-email-settings#20]
There is little in the way of documentation on how to access the system other that a reference to the trafeik port 8000, however this port is not mapped to the server. It would be great if a sample nginx configuration file were provided to illustrate how the system is port mapped and published.

**Comment by HLFH** [comment]
@madmath03 Hi. I guess nginx conf is quite easy to do. But it would also be great to run your project without Docker. Is it possible and made for purpose? Thanks

**Comment by HLFH** [comment]
Closed by: https://github.com/Monogramm/autodiscover-email-settings/pull/30

**Comment by madmath03** [comment]
Hello,

NGinx conf isn't too complicated, we can provide one in the README.
Regarding usage without docker, it's possible, just need to create a service and export all required environment variables to setup the service.

@HLFH I will update your PR and move the files into the README as those configuration cannot currently be tested automatically and are out of scope from the initial and recommended docker usage.
