### ISSUE TITLE
Make mobileconfig optional

### ISSUE THREAD

**Issue by xoxys** [Monogramm/autodiscover-email-settings#7]
Would it be possible to make Apple mobileconfig integration or at least the LDAP part optional? I don't have a proper LDAP server in place and I would like to avoid publishing dummy information.

**Comment by madmath03** [comment]
I do not think Mobileconfig itself can be optional, the URL will always exist, but it might be possible using [koa-swig](https://github.com/koa-modules/swig) to make the LDAP part optional.

Will look into that.

**Comment by madmath03** [comment]
@xoxys It's done.
New release 1.4.0 pushed with dynamic web page and autoconfig/autodiscover/mobileconfig.

**Comment by xoxys** [comment]
Thats pretty cool! Thanks a lot
